[tool.black]
line-length = 120

[tool.isort]
line_length = 120

[tool.mypy]
ignore_missing_imports = true

[tool.pylint.'MESSAGES CONTROL']
disable = ["C0116"]  # missing-function-docstring noise
extension-pkg-allow-list = []
max-line-length = 120
